### ISSUE TITLE
an example for visual servoing 

### ISSUE THREAD

**Issue by pxlong** [andyzeng/ikfastpy#1]
Hi @andyzeng, many thanks for open-sourcing this great repo for UR5. 

In the README, you mentioned that IKFast can be used with speedj command for real-time visual servoing. I am wondering do you have a example code for that?  How do you get the Jacobian of the UR5?

Thank you very much.

**Comment by suoyike1** [comment]
Hi @pxlong ,i do my Curriculum design recently about  real-time visual servoing. I have used servoj command but it didn't work perfectly. May I know that you have solve it or not? If is, would you release a litte demo code for that?
Thank you very much.
